### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions.

### ISSUE THREAD

**Issue by popescunsergiu** [rasjani/webdrivermanager#32] opened 2020-06-04 16:46 UTC
OS: macOS Catalina
Python: 3.8.2

When used by pytest-selenium it fails with: selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions.

A workaround is to do `sudo chmod 777 [path to chromedriver file]`

**Comment by rasjani** [comment] 2020-06-14 12:41
Can you reproduce this at will ? 

Are you using webdrivermanager via python or calling the cli ?

**Comment by rasjani** [comment] 2020-09-07 05:06
Cant reproduce, no feedback after initial comment. Closing

**Closed by rasjani** 2020-09-07 05:06 UTC
Labels: question
